export let Block: Set<any> = new Set();
export let Spawn: Set<any> = new Set();
export let Secret: Set<any> = new Set();
export let SecretObject:Set<any> = new Set()
export let Cave: Set<any> = new Set();
export let sets = [Block, Spawn, Secret, Cave];
export let outSets = [Block, Spawn, SecretObject, Cave];
export let allSets = [Block, Spawn, SecretObject,Secret, Cave]
export let setsString = ["Block", "Spawn", "Secret", "Cave"];